name: skies
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - numba
  - matplotlib
  - scikit-learn
  - pyproj
  - pandas
  - jupyterlab
  - ipympl
  - meshio
  - mlflow
  - pytest
  - addict
  - tqdm
  - h5py
  - colorcet
  - lxml
  - rich
  - compilers
  - fortran-compiler
  - cutde
  - ghostscript
  - pip
  - pip:
      - spherical_geometry
      - loguru
      - okada_wrapper
      - pygmt
      - pyvista
      - ismember
